name: Build CV

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-latex-extra
      - name: Compile CV
        run: pdflatex -interaction=nonstopmode cv.tex
      - uses: actions/upload-artifact@v3
        with:
          name: cv
          path: cv.pdf
      - name: Comment with artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = process.env.GITHUB_RUN_ID;
            const url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;
            const body = `CV PDF: [artifact download](${url})`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
