name: Build CV

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-latex-extra
      - name: Compile CV
        run: pdflatex -interaction=nonstopmode cv.tex
        continue-on-error: true
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
          if-no-files-found: warn
